### ISSUE TITLE
Search field is not searching in depth in object

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap-ui#103]
_From @apupier on October 11, 2017 12:50_

would be best to have a correct search if not possible it would be better to have at least a warning about it saying that the search is incomplete
Having a way to do a full search on demand even if it is taking will be nice.

I hit the issue when trying to follow the getting started searching for the screenName

![image](https://user-images.githubusercontent.com/1105127/31441464-8419ab04-ae93-11e7-90d2-d1364ecbd2bf.png)

_Copied from original issue: syndesisio/syndesis-datamapper#54_

**Comment by igarashitm** [comment]
duplicates #83 #94

**Comment by apupier** [comment]
please note that it is affecting the tutorial for TP1, should i open a different issue in documentation to modify it?

**Comment by igarashitm** [comment]
@apupier yes please, it's already saying that the search doesn't work for now for 'name' field, but it should say same for the other fields.

**Comment by apupier** [comment]
doc related issue https://github.com/syndesisio/syndesis-documentation/issues/25
