### ISSUE TITLE
AOT compile error

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap-ui#113]
As I've been doing some dependency updates I keep running into this error periodically until I find the magic combination of versions to bring in.  Am concerned that this could eventually be a problem.

<img width="836" alt="screenshot 2017-10-18 08 10 13" src="https://user-images.githubusercontent.com/351660/31719709-59e2b372-b3e2-11e7-859a-86b891da0682.png">

**Comment by gashcrumb** [comment]
The main thing I'm wondering is does this type change in newer angular versions:

https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/atlasmap-data-mapper/components/modal.window.component.ts#L66

and:

https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/atlasmap-data-mapper/components/modal.window.component.ts#L74

And also, would it make sense to consider migrating to the ngx-bootstrap modal window?

**Comment by gashcrumb** [comment]
@igarashitm awesome!  Does this then get automatically published to the npm repo?

**Comment by igarashitm** [comment]
@gashcrumb yep, 1.32.0-SNAPSHOT.20171018190510 has been published from CI :)
