### ISSUE TITLE
toggling show/hide mapped/unmapped fields causes syndesis ui to reset to home page

### ISSUE THREAD

**Issue by jbakermd** [atlasmap/atlasmap-ui#16]

**Comment by gashcrumb** [comment]
Probably from an `href="#"` in the `<a>`, lots of ways of handling this: https://stackoverflow.com/questions/35639174/passive-link-in-angular-2-a-href-equivalent

Easiest is to inline `$event.preventDefault()` where you do `(click)="doMyThing()"`

**Comment by jbakermd** [comment]
Oh man thanks for this. I was scratching my head on what was going on!

**Comment by jbakermd** [comment]
Although it is strange, two of the menu items (show lines, show types) don't have this problem. I'll dig into it.
