### ISSUE TITLE
Improve readme file. 

### ISSUE THREAD

**Issue by jbakermd** [atlasmap/atlasmap-ui#23]
Add the following updates to the readme/documentation:
- easiest way to install is with syndesis ui
- instructions for cloning / runing locally (including services setup)
- list libraries we depend on
- brief high level overview of what the ui does (service calls made, etc)
- brief overview of bootstrapping process
- list of project files w/ brief descriptions for each
- license terms

**Comment by jbakermd** [comment]
Ok I've knocked out a few of these readme updates per our discussion earlier this morning @mattrpav @kcbabo. There are still a few bullet points in this issue that are marked as TODO within the readme. Those will be addressed next week.

**Comment by jbakermd** [comment]
View the updated readme here:

https://github.com/atlasmap/atlasmap-ui

**Comment by kcbabo** [comment]
Nice!  @jpav @igarashitm --> FYI
