### ISSUE TITLE
Fix line drawing issue when scrolling through cards

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-ui#50]
1. Address UXD issue where line disappears during scroll
2. Maintain drawn line when scrolling cards
3. Line should maintain angle when target field is off screen
4. Line should stop at bottom of visible viewing area
5. Line may terminate to bottom of viewable area, and not directly to the Target field box
6. Should support both 'active' selected mapping and inactive mappings when the Show All Lines option is active

**Comment by jbakermd** [comment]
Missed the logic having math for target side too, fix incoming.
