### ISSUE TITLE
Update component to allow inspectionless initialization

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap-ui#51]
1. Update the atlasmap-ui component to support having the inspection data injected during component initialization
2. Support multi-source and single target initialization

**Comment by jbakermd** [comment]
This is done. Example code for reference @gashcrumb:

https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/syndesis-data-mapper/services/initialization.service.ts#L133

Code from there:

```
if (this.cfg.initCfg.addMockJavaCachedTarget) {
            console.error("INIT SERVICE MOCK DATA: Adding mock Java cache target document.");
            var docDef: DocumentDefinition = this.cfg.addJavaDocument("io.atlasmap.java.test.Name", false);
            docDef.initCfg.inspectionResultContents = DocumentManagementService.generateMockJavaDoc();
        }
```

(Note that the inspectionResultsContents var is doc type agnostic, you can specify it on java/xml/json documetns, not just java.)
