### ISSUE TITLE
Fake Mapping in table if no mapping has been created yet

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap-ui#58]
When clicking on a field in "Source" and then switch to the table view, a bogus entry has been created: 

![image](https://user-images.githubusercontent.com/99080/28612758-8e743aea-71f0-11e7-8301-3528bbe6feee.png)

This line vanishes immediately when another row in the table is selected

![image](https://user-images.githubusercontent.com/99080/28612792-aa1a89f2-71f0-11e7-967c-7266d08a1439.png)

**Comment by jbakermd** [comment]
Working as designed. Incomplete mappings (doesnt have at least one source and one target) are immediately deleted. When you had the single source selected that mapping was what we call a draft mapping, and is showing up as it currently exists. Then, when you selected an alternate mapping in the table the draft mapping was automatically discarded per requirement specs.

**Comment by jbakermd** [comment]
@rhuss review my comment above and lmk if you want to discuss further.

**Comment by rhuss** [comment]
ok, got it. The behaviour is a bit surprising to me (that something gets deleted when the focus changes), but I think there are more pressing issues. so let's close this issue.
