### ISSUE TITLE
Error Dialogs when removing mapping

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap-ui#59]
In the table view, when adding a new mapping and then immediately deleting it via the the trash can icon, then the following error dialogs appear:

![image](https://user-images.githubusercontent.com/99080/28656764-0c302cba-72a4-11e7-8b3f-cf5c7895d845.png)

Besides that I wouldn't expect an error here, the content of the  error message itself is not correct (or why should an error happen when something is supported ?)

**Comment by jbakermd** [comment]
Work on the validation engine in the atlas services side is ongoing. Let's leave this one open to verify those bogus validation errors disappear after the current crop of validation work happens.

**Comment by jbakermd** [comment]
This error message is fixed in the latest version of atlas.services. @rhuss  feel free to close when verified.

**Comment by igarashitm** [comment]
This will be addressed by #112
