### ISSUE TITLE
Getting compile error while bringing in latest commit

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap-ui#63]
Hey there!

Just thought I'd update to the current commit hash but hitting a compile error after pulling it in:

```
ERROR in C:/Users/gashcrumb/GitHub/syndesis-ui/node_modules/syndesis.data.mapper/src/app/lib/syndesis-data-mapper/components/line.machine.component.ts (235,99): ')' expected.

ERROR in C:/Users/gashcrumb/GitHub/syndesis-ui/node_modules/syndesis.data.mapper/src/app/lib/syndesis-data-mapper/components/line.machine.component.ts (235,99): ')' expected.
```

I updated my URL to this commit -> https://github.com/atlasmap/atlasmap-ui/commit/83500e5b485913a305d60609e9817fcf3371400a

**Comment by gashcrumb** [comment]
Ah, saw more PRs might be incoming, maybe I'll wait before pulling in the data mapper.

**Comment by jbakermd** [comment]
No, you're good. I merged this PR.

**Comment by jbakermd** [comment]
pull req: https://github.com/atlasmap/atlasmap-ui/pull/64
