### ISSUE TITLE
Show tooltips in datamapper ui toolbar

### ISSUE THREAD

**Issue by jludvice** [atlasmap/atlasmap-ui#71]
It might be challenging to find out what those icons mean
![toolbar](https://user-images.githubusercontent.com/8707241/30030055-e9bde2c4-918b-11e7-8c8a-65be74c5c34a.png)

**Comment by jludvice** [comment]
@gashcrumb can you take look on #72 please ?

It would be usefull also for E2E tests, as we can use tooltips to easily select DOM element like this:

```js
$('i[tooltip="Add new mapping"]')
$('i[tooltip="Editor settings"]')
```
CC @dsimansk @mmelko @lvydra

**Comment by igarashitm** [comment]
merged
