### ISSUE TITLE
Suggestion: "Show Lines" on by default.

### ISSUE THREAD

**Issue by rhuss** [atlasmap/atlasmap-ui#77]
I think it makes sense to always show all mapping lines by default, and let it be switchable to off from the menu. 

Actually, I always find myself to switch this on manually when I'm coming to the mappings. 

Confessedly this is a matter of taste but would like to start a small discussion here. Maybe there is a good reason to switch it off by default, too.

**Comment by gashcrumb** [comment]
I think by default we should actually show the table of mappings unless it's empty, and definitely 'show all lines' should default to on.

There's an issue discussing this here -> https://github.com/syndesisio/syndesis-ux/issues/37

**Comment by igarashitm** [comment]
+1

**Comment by igarashitm** [comment]
merged
