### ISSUE TITLE
Suggestion: Show a tooltip on each field

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap-ui#78]
Currently I can't see the data type of the fields unless I actually select it, which means new mapping is created anyway. This is annoying when I'm just looking around the data type. I think It helps if a tooltip shows type and path.

**Comment by abkieling** [comment]
@igarashitm is this issue still relevant?

**Comment by igarashitm** [comment]
Yes, but we haven't yet agreed to implement it
