### ISSUE TITLE
Update rxjs imports

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap-ui#87]
Some of these imports seem to cause problems when trying to import the component into a new angular project, such as:

```
import { Observable } from 'rxjs/Rx';
import { Subject } from 'rxjs/Subject';
import 'rxjs/add/operator/toPromise';
import 'rxjs/add/observable/forkJoin';
import 'rxjs/add/operator/map';
```

I think Observable should be imported from rxjs/Observable.  Also it may not be necessary with more recent rxjs versions to import the operators.

@chirino FYI

**Comment by gashcrumb** [comment]
Main issue are these files:

https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/syndesis-data-mapper/services/document.management.service.ts
https://github.com/atlasmap/atlasmap-ui/blob/master/src/app/lib/syndesis-data-mapper/services/mapping.management.service.ts

When you import the data mapper into a new project you get compile errors from the toPromise() calls.

**Comment by igarashitm** [comment]
Fixed that Observable import. Let's see if there's anything else.

**Comment by igarashitm** [comment]
closing, now it looks fine
